In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
model = nn.Linear(1,1)

In [5]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [6]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

In [7]:
nb_epochs=2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)

  cost = F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [8]:
new_var =  torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) 

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward>)


In [9]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [10]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [12]:
del(model)

In [13]:
model = nn.Linear(3,1)

In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1188,  0.2937,  0.0803]], requires_grad=True), Parameter containing:
tensor([-0.0707], requires_grad=True)]


In [15]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [16]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)

  cost = F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 22642.416016
Epoch  100/2000 Cost: 4.976951
Epoch  200/2000 Cost: 4.733481
Epoch  300/2000 Cost: 4.502824
Epoch  400/2000 Cost: 4.284275
Epoch  500/2000 Cost: 4.077209
Epoch  600/2000 Cost: 3.881021
Epoch  700/2000 Cost: 3.695124
Epoch  800/2000 Cost: 3.519025
Epoch  900/2000 Cost: 3.352130
Epoch 1000/2000 Cost: 3.194023
Epoch 1100/2000 Cost: 3.044178
Epoch 1200/2000 Cost: 2.902206
Epoch 1300/2000 Cost: 2.767665
Epoch 1400/2000 Cost: 2.640176
Epoch 1500/2000 Cost: 2.519374
Epoch 1600/2000 Cost: 2.404892
Epoch 1700/2000 Cost: 2.296402
Epoch 1800/2000 Cost: 2.193589
Epoch 1900/2000 Cost: 2.096157
Epoch 2000/2000 Cost: 2.003828


In [17]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.9719]], grad_fn=<AddmmBackward>)


In [18]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.6294, 0.6883, 0.6936]], requires_grad=True), Parameter containing:
tensor([-0.0603], requires_grad=True)]
